Added new ios integration methods documentation.
userzoom/UserZoomSDK-docs pull request #1
Opened 2021-09-17 08:35 UTC by pbiosca-uz

2021-09-21 16:00 UTC, gahing-uz commented on ios/sdk-ios-faq.md
> +- [How fix cocoapods could not find compatible versions for pod?](#how-fix-cocoapods-could-not-find-compatible-versions-for-pod)
How do I fix cocoapods could not find compatible versions for pod?

2021-09-21 16:00 UTC, gahing-uz commented on ios/sdk-ios-faq.md
> +## How fix CocoaPods could not find compatible versions for pod?
How to fix CocoaPods could not find compatible versions for pod

2021-09-21 16:01 UTC, gahing-uz commented on ios/sdk-ios-faq.md
> +If when you run the command `pod install`, you are getting this fail: CocoaPods could not find compatible versions for pod "DatadogSDKObjC
If when you run the command `pod install`, you are getting this error: CocoaPods could not find compatible versions for pod "DatadogSDKObjC

2021-09-21 16:02 UTC, gahing-uz commented on ios/sdk-ios-setup.md
> +To integrate UserzoomSDK into your Xcode project using Swift Package Manager, you need add the repository url UserzoomSDK in your package.swift file or in Xcode, select File ▸ Swift Packages ▸ Add Pa
To integrate the UserzoomSDK into your Xcode project using Swift Package Manager, you need to add the repository url UserzoomSDK in your package.swift file or in Xcode, select File ▸ Swift Packages ▸ Add Package Dependency… :

2021-09-21 16:07 UTC, gahing-uz requested changes
Check the in line comments to see the requested changes.

2021-09-23 09:20 UTC, msobiepanek-uz approved these changes

2021-09-27 10:32 UTC, gahing-uz approved these changes

2021-12-15 14:44 UTC, merged